<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.4.1-alpha
 * FormDin Version: 4.5.3-alpha
 * 
 * System sort created in: 2019-05-06 18:55:08
 */

defined('APLICATIVO') or die();
$frm = new TForm('Resultado',800);
$frm->setShowCloseButton(false);
$frm->setFlat(true);
$frm->setMaximize(true);


$dados = $_SESSION[APLICATIVO]['COMTEMPLADOS'];
$gride = new TGrid('gdComtemplados' // id do gride
                , 'Lista de Comtemplados' // titulo do gride
                , $dados   // array de dados
                );     // chave primaria


$gride->addColumn('LINHA', 'Posição');
//$gride->addColumn('KEYO', 'Ativo');
$gride->addColumn('VALOR', 'Nome');
$gride->enableDefaultButtons(false);
$frm->addHtmlField('grideComtemplados', $gride);


$dados = $_SESSION[APLICATIVO]['FILAESPERA'];
$gride = new TGrid('gdEspera' // id do gride
                , 'Fila de Espera' // titulo do gride
                , $dados   // array de dados
                );     // chave primaria


$gride->addColumn('LINHA', 'Posição');
//$gride->addColumn('KEYO', 'Ativo');
$gride->addColumn('VALOR', 'Nome');
$gride->enableDefaultButtons(false);
$frm->addHtmlField('grideEspera', $gride);


$frm->show();

?>