<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.4.1-alpha
 * FormDin Version: 4.5.3-alpha
 * 
 * System sort created in: 2019-05-06 18:55:08
 */

defined('APLICATIVO') or die();
$arquivoMateria = 'arquivoMateria';
$frm = new TForm('Sorteio de Nomes');
$frm->setShowCloseButton(false);
$frm->setFlat(true);
$frm->setMaximize(true);

$frm->addNumberField('QTD', 'Quantidade:', 5, true, 0, true, null, 5, null, null, null, true, true);
$frm->addFileField($arquivoMateria,'Arquivo:',true,'txt','1M',40,true);

$frm->addButton('Salvar', null, 'Salvar', null, null, true, false);
$frm->addButton('Limpar', null, 'Limpar', null, null, false, false);

function getPostArquivoMateria(&$frm,$arquivoMateria){
    $postArquivoMateria['arquivoMateria_name']      = PostHelper::get($arquivoMateria);
    $postArquivoMateria['arquivoMateria_temp_name'] = $frm->getBase().PostHelper::get($arquivoMateria.'_temp_name');
    $postArquivoMateria['arquivoMateria_extension'] = PostHelper::get($arquivoMateria.'_extension');
    $postArquivoMateria['arquivoMateria_size']      = PostHelper::get($arquivoMateria.'_size');
    $postArquivoMateria['arquivoMateria_type']      = PostHelper::get($arquivoMateria.'_type');

    return $postArquivoMateria;
}


$acao = isset($acao) ? $acao : null;
switch( $acao ) {
    //--------------------------------------------------------------------------------
    case 'Limpar':
        $frm->clearFields();
    break;
    case 'Salvar':
        try{
            if ( $frm->validate() ) {
                $postArquivoMateria = getPostArquivoMateria($frm,$arquivoMateria);
                var_dump($postArquivoMateria);
                $class = new Sorteio();
                $qtd = $frm->getFieldValue('QTD');
                $resultado = $class->sortear($qtd,$postArquivoMateria);
                if($resultado==1) {
                    $frm->setMessage('Registro gravado com sucesso!!!');
                    $frm->clearFields();
                }else{
                    $frm->setMessage($resultado);
                }
            }
        }
        catch (DomainException $e) {
            $frm->setMessage( $e->getMessage() );
        }
        catch (Exception $e) {
            MessageHelper::logRecord($e);
            $frm->setMessage( $e->getMessage() );
        }
    break;
}


function getWhereGridParameters(&$frm)
{
    $retorno = null;
    if($frm->get('BUSCAR') == 1 ){
        $retorno = array(
                'SEQ_DADO_APOIO'=>$frm->get('SEQ_DADO_APOIO')
                ,'SEQ_DADO_APOIO_PAI'=>$frm->get('SEQ_DADO_APOIO_PAI')
                ,'TIP_DADO_APOIO'=>$frm->get('TIP_DADO_APOIO')
                ,'SIG_DADO_APOIO'=>$frm->get('SIG_DADO_APOIO')
                ,'BOL_CANCELADO'=>$frm->get('BOL_CANCELADO')
        );
    }
    return $retorno;
}

if( isset( $_REQUEST['ajax'] )  && $_REQUEST['ajax'] ) {
    $maxRows = ROWS_PER_PAGE;
    $whereGrid = getWhereGridParameters($frm);
    $dados = Dado_apoio::selectAll( $primaryKey, $whereGrid );
    $mixUpdateFields = $primaryKey.'|'.$primaryKey
                    .',SEQ_DADO_APOIO_PAI|SEQ_DADO_APOIO_PAI'
                    .',TIP_DADO_APOIO|TIP_DADO_APOIO'
                    .',SIG_DADO_APOIO|SIG_DADO_APOIO'
                    .',BOL_CANCELADO|BOL_CANCELADO'
                    ;
    $gride = new TGrid( 'gd'                        // id do gride
    				   ,'Gride with SQL Pagination' // titulo do gride
    				   );
    $gride->addKeyField( $primaryKey ); // chave primaria
    $gride->setData( $dados ); // array de dados
    $gride->setMaxRows( $maxRows );
    $gride->setUpdateFields($mixUpdateFields);
    $gride->setUrl( 'dado_apoio.php' );

    $gride->addColumn($primaryKey,'id');
    $gride->addColumn('SEQ_DADO_APOIO_PAI','SEQ_DADO_APOIO_PAI');
    $gride->addColumn('TIP_DADO_APOIO','TIP_DADO_APOIO');
    $gride->addColumn('SIG_DADO_APOIO','SIG_DADO_APOIO');
    $gride->addColumn('BOL_CANCELADO','BOL_CANCELADO');


    $gride->show();
    die();
}

$frm->addHtmlField('gride');
$frm->addJavascript('init()');
$frm->show();

?>
<script>
function init() {
    var Parameters = {"BUSCAR":""
                    ,"SEQ_DADO_APOIO":""
                    ,"SEQ_DADO_APOIO_PAI":""
                    ,"TIP_DADO_APOIO":""
                    ,"SIG_DADO_APOIO":""
                    ,"BOL_CANCELADO":""
                    };
    fwGetGrid('dado_apoio.php','gride',Parameters,true);
}
function buscar() {
    jQuery("#BUSCAR").val(1);
    init();
}
</script>