<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.4.1-alpha
 * FormDin Version: 4.5.3-alpha
 * 
 * System sort created in: 2019-05-06 18:54:59
 */

define('BANCO'   , 'SQLITE');
define('HOST'    , '');
define('PORT'    , '');
define('DATABASE', 'bancos_locais/bdApoio.s3db');
define('SCHEMA'  , '');
define('USUARIO' , '');
define('SENHA'   , '');
define('UTF8_DECODE'   , 0);
?>