<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.4.1-alpha
 * FormDin Version: 4.5.3-alpha
 * 
 * System sort created in: 2019-05-06 18:54:59
 */

define('SYSTEM_NAME'    , 'Sorteio de Inscritos');
define('SYSTEM_ACRONYM' , 'sort');
define('SYSTEM_VERSION' , '0.0.0');
define('APLICATIVO'     , SYSTEM_ACRONYM);

define('FORMDIN_VERSION_MIN_VERSION', '4.5.2');

if (! defined ( 'DS' )) {
    define('DS'   , DIRECTORY_SEPARATOR);
}
?>